// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP2ANklS6IufFY0W09-4ITDLHyxsgIXK8',
    appId: '1:256183224495:web:3e2b5575a06c9c951dac5a',
    messagingSenderId: '256183224495',
    projectId: 'course-ad22a',
    authDomain: 'course-ad22a.firebaseapp.com',
    databaseURL: 'https://course-ad22a-default-rtdb.firebaseio.com',
    storageBucket: 'course-ad22a.appspot.com',
    measurementId: 'G-SVMG3QG9KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-EgfJqo4M_eXMBPi3rSdpDdsXC0x74P8',
    appId: '1:256183224495:android:2dfd4cae5bd66fae1dac5a',
    messagingSenderId: '256183224495',
    projectId: 'course-ad22a',
    databaseURL: 'https://course-ad22a-default-rtdb.firebaseio.com',
    storageBucket: 'course-ad22a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB34t5Vfj-ecAOux_atDFyLwRkb8VL9yAI',
    appId: '1:256183224495:ios:bc14894ffdac72b91dac5a',
    messagingSenderId: '256183224495',
    projectId: 'course-ad22a',
    databaseURL: 'https://course-ad22a-default-rtdb.firebaseio.com',
    storageBucket: 'course-ad22a.appspot.com',
    iosBundleId: 'com.example.dars75YandexmapRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB34t5Vfj-ecAOux_atDFyLwRkb8VL9yAI',
    appId: '1:256183224495:ios:bc14894ffdac72b91dac5a',
    messagingSenderId: '256183224495',
    projectId: 'course-ad22a',
    databaseURL: 'https://course-ad22a-default-rtdb.firebaseio.com',
    storageBucket: 'course-ad22a.appspot.com',
    iosBundleId: 'com.example.dars75YandexmapRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP2ANklS6IufFY0W09-4ITDLHyxsgIXK8',
    appId: '1:256183224495:web:91bb373f3ce9acf41dac5a',
    messagingSenderId: '256183224495',
    projectId: 'course-ad22a',
    authDomain: 'course-ad22a.firebaseapp.com',
    databaseURL: 'https://course-ad22a-default-rtdb.firebaseio.com',
    storageBucket: 'course-ad22a.appspot.com',
    measurementId: 'G-5K3LQ8EW0G',
  );
}
